import Head from 'next/head'
import styles from '@/styles/Home.module.css'

const AboutPage = () => (
    <>
        <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
        <div className={styles.center}>
            <h1>About page</h1>
        </div>
        </main>
    </>
)

export default AboutPage
