import Head from 'next/head'
import styles from '@/styles/Home.module.css'

const ContactPage = () => (
    <>
      <Head>
        <title>Contact page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
            <h1>Contact page</h1>
        </div>
      </main>
    </>
)

export default ContactPage
