export {About} from './About'
export {Contact} from './Contact'
export {default as Home} from './Home'
export {default as Main} from './Main'
export {default as Projects} from './Projects'
export {Experience} from './Experience'
